name: Routine testing

on: 
  schedule:
    - cron: '0 0 * * 1'
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
        pip install numpy
        pip install scipy
    - name: Test with pytest
      run: |
        pip install pytest pytest-cov
        pytest --junitxml=junit/test-results-${{ matrix.os }}.xml
    - name: Upload pytest test results
      uses: actions/upload-artifact@v4
      with:
        name: pytest-results-${{ matrix.os }}
        path: junit/test-results-${{ matrix.os }}.xml
      # Use always() to always run this step to publish test results when there are test failures
      if: ${{ always() }}
